# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0003_auto_20170924_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mobile_api.UserGroup'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_user_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
