# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0004_auto_20170924_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mobile_api.Event'),
        ),
    ]
