# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0005_transaction_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
