# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0006_transaction_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_paid_for_group',
            field=models.BooleanField(default=False),
        ),
    ]
