# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0007_transaction_is_paid_for_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_money',
            field=models.SmallIntegerField(choices=[(0, b'Group'), (1, b'Individual')], default=0),
        ),
    ]
