# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0008_event_source_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member_join',
            field=models.TextField(null=True),
        ),
    ]
