# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0009_event_member_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slack_id',
            field=models.TextField(default=b'', null=True),
        ),
    ]
